// let score="33";
// console.log(typeof score);
// let value=Number(score);
// console.log(typeof value);
// console.log(value);
// let score=true;
// console.log(typeof score);
// let value=Number(score);
// console.log(typeof value);
// console.log(value);
let score="ALOK";
console.log(typeof score);
let value=Number(score);
console.log(typeof value);
console.log(value);